### ISSUE TITLE
transactionService->getDataFor*Ui() methods 

### ISSUE THREAD

**Issue by roma-glushko** [wirecard/paymentSDK-php#178]
Hello, guys!

I've noticed that you implemented the following method:
**$transactionService->getDataForCreditCardUi()**
As far as I see, it does zero payment authorization for the credit card payment method in the seamless integration.
Thought there is only one such methods. In theory, there should be implemented such methods for other payment methods (like SEPA, IDEAL).

Am I right? Is there a way to render forms for other payment methods in the same way as it was done for the creditcard payment method (using API from the paymentPageLoader.js library)?

Looking forward to you feedback!
Thanks.

**Comment by horfic** [comment]
Hi,
the paymentPageLoader.js is only used for credit card form rendering as this will minimize PCI security for the merchant. The credit card form is an iframe which is hosted by wirecard, so the merchant never has the ability to access the credit card data.

For other payment methods like SEPA, IDEAL, etc this is not needed and also not available per paymentPageLoader.js.

This also provides better customization for the merchant as all fields like IBAN, BIC, etc can be normal html form elements and be styled to the merchant liking. Except for the credit card form, styling is limited here as this part is hosted at wirecard.

Hope that answers your question.
Horst

**Comment by roma-glushko** [comment]
Hi @horfic , Thank you for the answer!
