### ISSUE TITLE
Credit card authorize

### ISSUE THREAD

**Issue by horfic** [wirecard/paymentSDK-php#25]
As developer of a shop-plugin based on EE I am able to integrate credit card as payment method, so that an amount is reserved on a consumer credit card during payment.

Acceptance criteria:
 - example with documentation is available
 - As a developer I can use the example without changes "out-of-the-box" on my web-server.
 - php-versions >= 5.6 are supported
 - Successful credit card authorization and error handled

**Comment by JuEger** [comment]
Tasks for SSL authorizations:
- [ ] add preperation of Ui From Data to TransactionService (getDataForCreditCardUi)
  - [ ] Implementation
  - [ ] Example
- [ ] Add SSL Transaction entity
- [ ] Add credit card specific Request Mapper
- [ ] Add reserve to TransactionService
  - [ ] implementation
  - [ ] example
