### ISSUE TITLE
Payment Iframe not stylable

### ISSUE THREAD

**Issue by voodoo44** [wirecard/paymentSDK-php#271]
I just used your library to implement SEPA Transactions.
Now i wanted to integrate the "create-ui"-example from this library and everything works as expected. But there are no options to style the content of the iframe.
Are there options style this iframe? cssUrl and iframeCssUrl won't do.

**Comment by jakubpolomsky** [comment]
I believe you are referring to the credit card. If it is correct, I'd have to advise you to our [seamless integration help](https://document-center.wirecard.com/display/PTD/Seamless+Configuration+UI) if not, then you will find the example on how we produce the form in [this](https://github.com/wirecard/paymentSDK-php/blob/master/examples/Sepa/reserve.php) file.
