### ISSUE TITLE
How to delete customer's information

### ISSUE THREAD

**Issue by kakasal** [wirecard/paymentSDK-php#288]
I want to remove customer's credit card info or customer profile. Is it possible? Why it is not included in the API/SDK?

**Comment by jakubpolomsky** [comment]
Hello,

can you please explain what exactly do you mean? This sdk doesn't have any persitence layer. Any meaning not even session or cookies. If you would be so kind and explained to us what you'd like to achieve we'll be happy to help you or maybe even implement it.

Kind regards

**Comment by shlaing** [comment]
For example , You create the card via tokenization. 
In the business logic, if user want to remove the credit card information that is created inside the wirecard,
we need to remove it back.  That is what I understand.

**Comment by kakasal** [comment]
We have implemented payment using the seamless method. Now when our customers deletes/cancels their account we want to wash-off all data from wiredcard as well.
Wirecard documentation is extremely insufficiency. I event did not find the word cancel/delete etc in their entire documentation.
