### ISSUE TITLE
Send mixed Shopping Baskets to Paypal and SOFORT

### ISSUE THREAD

**Issue by gunterthomas** [wirecard/paymentSDK-php#305]
I want to use the possibility of Paypal to send mixed shopping baskets to Paypal (I think they call it "parallel payments") - we need to add several parallel payments in one basket (e.g. one or two "one time" payments and 1 oder 2 recurring payments) within ONE transaction - at the moment it looks like wirecard does not support this.

**Comment by jakubpolomsky** [comment]
Hello!

Thank you for asking. We have forwarded this question to my colleagues who are responsible for the API. Immediately when we receive the answer we will update you.

Kind regards

**Comment by jakubpolomsky** [comment]
Hello once again,

after receiving the answer to your question from my colleagues I can tell you that wirecard really does not support this feature yet. I have to close this issue now. 

Have a nice day!
