### ISSUE TITLE
php-http/client-implementation package not found during installation via composer

### ISSUE THREAD

**Issue by sydekumf** [wirecard/paymentSDK-php#311]
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                                        
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wirecard/payment-sdk-php 3.0.0 -> satisfiable by wirecard/payment-sdk-php[3.0.0].
    - wirecard/payment-sdk-php 3.0.0 requires php-http/client-implementation ^1.0 -> no matching package found.
```

**Comment by rinnhofer** [comment]
Hello,
sorry for the late replay. It is hard to tell what went wrong in your composer update process. Are you using composer for other libraries in your project too or do you only use it for paymentSDK-php?
If you are using only paymentSDK-php via composer try to delete the composer.lock file and retry "composer install".
If you are using other libraries in your project too, or a specific http client maybe you need to define a compatible http client in your requirements (no-dev).

Kind regards
