### ISSUE TITLE
Fatal error: Response is not a valid xml string

### ISSUE THREAD

**Issue by masitings** [wirecard/paymentSDK-php#526]
Hi there i want to ask about the error that i've face using CreditCard 3D Secure Page i have look into the examples files and so far its going smoothly. Short story im facing the error after submit the from on 3D Secure Page it says like this 

`Fatal error: Uncaught Wirecard\PaymentSdk\Exception\MalformedResponseException: Response is not a valid xml string. in /var/www/fixxdigital/orange/wp-content/themes/orangeclove/vendor/wirecard/payment-sdk-php/src/Mapper/ResponseMapper.php:122 Stack trace: #0 /var/www/fixxdigital/orange/wp-content/themes/orangeclove/vendor/wirecard/payment-sdk-php/src/TransactionService.php(628): Wirecard\PaymentSdk\Mapper\ResponseMapper->map('<html><head><ti...', Object(Wirecard\PaymentSdk\Transaction\CreditCardTransaction)) #1 /var/www/fixxdigital/orange/wp-content/themes/orangeclove/vendor/wirecard/payment-sdk-php/src/TransactionService.php(772): Wirecard\PaymentSdk\TransactionService->process(Object(Wirecard\PaymentSdk\Transaction\CreditCardTransaction), 'authorization') #2 /var/www/fixxdigital/orange/wp-content/themes/orangeclove/vendor/wirecard/payment-sdk-php/src/TransactionService.php(197): Wirecard\PaymentSdk\TransactionService->processAuthFrom3DResponse(Array) #3 /var/www/fixxdigital/orange/wp-content/themes/orangeclove/app/contr in /var/www/fixxdigital/orange/wp-content/themes/orangeclove/vendor/wirecard/payment-sdk-php/src/Mapper/ResponseMapper.php on line 122`

**Comment by tomazpu** [comment]
Hello, 

thank you for your issue. I would need more info's about what exactly you are doing. My hint is are you using the processJsResponse() to process the credit card response? If not can u please write the version of the paymentSDK-php, php version and the code snippet of how you are using it. 

Best regards,
Tomaz

**Comment by serucee** [comment]
Closed due to inactivity.
