### ISSUE TITLE
Basket#parseFromXml() does not add the tax-rate if set

### ISSUE THREAD

**Issue by ps-cgrach** [wirecard/paymentSDK-php#533]
`\Wirecard\PaymentSdk\Entity\Basket#parseFromXml($simpleXml)` only adds the `tax-amount` from the xml but not the `tax-rate` if that tag is provided.
See `\Wirecard\PaymentSdk\Transaction\RatepayInvoiceTransaction` for example.

**Comment by tomazpu** [comment]
Hello @ps-cgrach,

thank you for your contribution, we will look into that issue.

Best regards,
Tomaz
