### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by masitings** [wirecard/paymentSDK-php#553]
Hi i got this error when i attempt to pay : 

> Error getting response from Tokenization (remote) Server

are this was kind of server point issues ? are there's something wrong with my code ?

**Comment by jakubpolomsky** [comment]
It is possible that the server failed to respond. I have checked the status right now and tried to do a checkout with the examples and everything worked properly. Would you mind checking again and closing the issue? Should the problem persist for you I would suggest contacting the support with your exact request and response data.

Kind regards,
Team Wirecard

**Comment by rinnhofer** [comment]
Hello @masitings ,

since it seems that everything worked out for you and there are no additional questions I will close this issue now. Please, feel free to open a new issue if there is still something wrong or your need help.

Kind regards,
Wirecard Shop Systems Team

**Comment by masitings** [comment]
Thanks, its server issue.. now its work properly
