### ISSUE TITLE
An SDK licensed under the GPL?!

### ISSUE THREAD

**Issue by JanSlabon** [wirecard/paymentSDK-php#559]
We, as a customer, are forced to switch to "Wirecard Payment Page v2" until 14th September 2019. Short time frame... but that's not the main problem for us.

For the old version there was no offical SDK available but an [unofficial SDK](https://github.com/hochstrasserio/wirecard) that was developed by individuals under a great license (MIT) which worked and still works flawless.

Great to see that there is an official SDK available now. Anyhow, you released it under the GPL v3?
For sure this means that this SDK cannot be used in any proprietary solution... such as our own systems :-/

Not so say that this license is incompatible to the licenses of shop systems you wrote modules for. E.g. Magento is licensed under the [OSL 3.0](https://magento.com/legal/licensing) which is an [incomptible license](https://www.gnu.org/licenses/license-list.en.html#OSL) to the GPL. Same for [Prestashop](https://www.prestashop.com/en/osl-license).

Why isn't this dual licensed or at least with a more less restrictive license? GPL is the worst choice for this IMHO.

**Comment by vitali-graz** [comment]
Hi @JanSlabon 
Thank you for bringing up this issue. We are currently discussing and evaluating this internally.
Best regards,
Vitali Auracher
Business Analyst Shop Systems

**Comment by JanSlabon** [comment]
One month left... Any news on this?

**Comment by vitali-graz** [comment]
Hi @JanSlabon 
We are likely to replace GPL with MIT in the near future - this quiestion is currently being decided by our legal department. I'm expecting a response within the next two weeks.
Best regards,
Vitali Auracher
Business Analyst Shop Systems

**Comment by vitali-graz** [comment]
Quick update, our SDK is now licensed under MIT.
Best regards,
Vitali Auracher
Business Analyst Shop Systems

**Comment by JanSlabon** [comment]
Ok, so when can we expect an official release?
