### ISSUE TITLE
The Amount has not the expected number of fractional digits

### ISSUE THREAD

**Issue by RF1705** [wirecard/paymentSDK-php#587]
i want to refund 12.34, but i get the issue: The Amount has not the expected number of fractional digits.

the only solution ist to cast the Amount in the Amount.php

   public function mappedProperties()
    {
        return [
            'currency' => $this->currency,
            'value' => (string) $this->value
        ];
    }

**Comment by rinnhofer** [comment]
Hello @RF1705 ,

thank you for your contribution. I am sorry, but I am not sure what you try to do. 
Could you please explain more detailed what exactly is the problem and add steps to reproduce?
A code snippet could help us to understand the issue too.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @RF1705,

I will close this issue since there was no feedback from your side. Feel free to open a new issue if you need any help. 

Kind regards, 
Wirecard Shop Systems Team
