### ISSUE TITLE
Mandate are always current date

### ISSUE THREAD

**Issue by cbou** [wirecard/paymentSDK-php#588]
The Mandate class does not allow to add a custom Mandate Date.
Since the documentation specify `This is the date on which the above-mentioned mandate was signed by the consumer.`.

How to use this class for recurring payment with SEPA Direct Debit?

**Comment by serucee** [comment]
Hi,

thank you for your input. We will look into the described issue and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by cpfoser** [comment]
Hi @cbou,

for SEPA Direct Debit payments it is important to use the date where the consumer has signed the mandate (date for initial transaction). Our payment-SDK does not support recurring payment with SEPA Direct Debit and it is currently not planned.

Best regard,
Wirecard Shop Systems Team

**Comment by cbou** [comment]
Ok Thanks

For those who are interested it's quite easy to override and improve the Mandate class. The recurring payments seem to work after that.

```
<?php

namespace MyNamespace;

use Wirecard\PaymentSdk\Entity\MappableEntity;

class Mandate implements MappableEntity
{
    /**
     * @var string
     */
    private $id;
	
    /**
     * @var string
     */
    private $signedDate;

    /**
     * Mandate constructor.
     * @param string $id
     * @param string $signedDate
     */
    public function __construct($id, $signedDate)
    {
        $this->id = $id;
        $this->signedDate = $signedDate;
    }

    public function mappedProperties()
    {
        return [
            'mandate-id' => $this->id,
            'signed-date' => gmdate($this->signedDate)
        ];
    }
}

```
